version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: db_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  api:
    build: .
    container_name: api_container
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo

volumes:
  mongo_data:
    